const add=require('./add')
const substract=require('./substract')
const devide=require('./devide')
const multiply=require('./multiply')
// const a=add(1+2)
console.log(add(1,2))
console.log(substract(1,2))
console.log(devide(1,2))
console.log(multiply(1,2))